services:

  db:
    image: mysql:8.0                 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   
      MYSQL_DATABASE: liveklass_events  
      MYSQL_USER: ${MYSQL_USER}               
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}        
    ports:
      - "3307:3306"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  
      interval: 5s                    
      timeout: 5s                     
      retries: 10                     

  producer:
    build: ./producer                 
    env_file: .env                    
    depends_on:
      db:
        condition: service_healthy    

volumes:
  db_data:                           
